branch-defaults:
  default:
    environment: wormie-4-dev
    group_suffix: null
global:
  application_name: wormie-4
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-1
  profile: eb-cli
  sc: null
