branch-defaults:
default:
  environment: wormie-3-dev
  group_suffix: null
global:
application_name: wormie-3
default_ec2_keyname: aws-eb
default_platform: Python 3.4
default_region: us-west-1
profile: eb-cli
sc: null
